language: python
dist: xenial
sudo: false
python:
- '3.6'
- '3.7'
before_install:
- export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
- pip install python-coveralls
- pip install pytest
- pip install pytest-cov
- pip install .
script:
- pytest --cov=fileparse fileparse
after_success:
- coveralls
deploy:
  provider: pypi
  user: __token__
  password:
    secure: BboxByB+w3xHolDUPklUYI2VUyZqlRjIy4FeVBzgCS7TNRQXozAEIpllf5AB5CM5ZvfPLyqsBz75MX7xdfBuCSbXtykhttAcUqhER/YM6maf4Y8YhbnUCJVEsU50h78ekCWijgLtZ4sxFUPjA47A7fhGcvwtM1de9p4S2+7Zp0suHgSAj6/Bbj0TQza7WbxOzEPkaB44UnmVQvdVoTgxtMKN1SbeYyGXfm9+oPiXjNOrTP5WCWJLaGqL4s3XPxw1lichWGC/kkn3yJI/JrwXOKpPQAO5YXEut6A+qoiHxPYOQhNQwtNbfy6pIrjUDmF0gtLpOt9KEzW2otqwkhZVHjTAqJDCW8SZEhWaK9dXKPXllikxYk1fsZImMfPcJxciDUOneLqb6ZcRtExxeKBhQwUk6X5G+er4nHz6daFtKLOVAQCiPuc000gQeAYD2dQrg5UsFvoUZT2doMDztZQjn5IMAzHHb3DEJF8dJrbrAWLWlwjBFuyHCTPtuth9qB7qKTzRWBZfVLI4eiYLbHf2HljQUcMu5r1y6JkmTXVjlTuNGLqCc2VN8SFDMOSXpxNYvzuKQAUmEmVF0ZRY9tpIedgcOHisN9DYQlbFP6WPC6zpjxTEEMdesaD8B4EuAAeFjv8FBRyVj9Cp003mTgrBoepDeHSITMR6oXRYg2u+4LY=
  on:
    branch: master
  skip_existing: true
